// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/messages/NaturalPerson.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Messages {

  /// <summary>Holder for reflection information generated from proto_defs/messages/NaturalPerson.proto</summary>
  public static partial class NaturalPersonReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/messages/NaturalPerson.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NaturalPersonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidwcm90b19kZWZzL21lc3NhZ2VzL05hdHVyYWxQZXJzb24ucHJvdG8SHFZp",
            "cnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMaIHByb3RvX2RlZnMvbWVzc2Fn",
            "ZXMvUGVyc29uLnByb3RvIrYBCg1OYXR1cmFsUGVyc29uEjQKBnBlcnNvbhgB",
            "IAEoCzIkLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuUGVyc29uEksK",
            "C2dlbmRlcl90eXBlGAIgASgOMjYuVmlydHVhbFdhbGxldC5Qcm90by5NZXNz",
            "YWdlcy5OYXR1cmFsUGVyc29uLkdlbmRlclR5cGUiIgoKR2VuZGVyVHlwZRII",
            "CgRNQUxFEAASCgoGRkVNQUxFEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VirtualWallet.Proto.Messages.PersonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualWallet.Proto.Messages.NaturalPerson), global::VirtualWallet.Proto.Messages.NaturalPerson.Parser, new[]{ "Person", "GenderType" }, null, new[]{ typeof(global::VirtualWallet.Proto.Messages.NaturalPerson.Types.GenderType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class NaturalPerson : pb::IMessage<NaturalPerson> {
    private static readonly pb::MessageParser<NaturalPerson> _parser = new pb::MessageParser<NaturalPerson>(() => new NaturalPerson());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NaturalPerson> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualWallet.Proto.Messages.NaturalPersonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NaturalPerson() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NaturalPerson(NaturalPerson other) : this() {
      Person = other.person_ != null ? other.Person.Clone() : null;
      genderType_ = other.genderType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NaturalPerson Clone() {
      return new NaturalPerson(this);
    }

    /// <summary>Field number for the "person" field.</summary>
    public const int PersonFieldNumber = 1;
    private global::VirtualWallet.Proto.Messages.Person person_;
    /// <summary>
    /// Base message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VirtualWallet.Proto.Messages.Person Person {
      get { return person_; }
      set {
        person_ = value;
      }
    }

    /// <summary>Field number for the "gender_type" field.</summary>
    public const int GenderTypeFieldNumber = 2;
    private global::VirtualWallet.Proto.Messages.NaturalPerson.Types.GenderType genderType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VirtualWallet.Proto.Messages.NaturalPerson.Types.GenderType GenderType {
      get { return genderType_; }
      set {
        genderType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NaturalPerson);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NaturalPerson other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Person, other.Person)) return false;
      if (GenderType != other.GenderType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (person_ != null) hash ^= Person.GetHashCode();
      if (GenderType != 0) hash ^= GenderType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (person_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Person);
      }
      if (GenderType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GenderType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (person_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Person);
      }
      if (GenderType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GenderType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NaturalPerson other) {
      if (other == null) {
        return;
      }
      if (other.person_ != null) {
        if (person_ == null) {
          person_ = new global::VirtualWallet.Proto.Messages.Person();
        }
        Person.MergeFrom(other.Person);
      }
      if (other.GenderType != 0) {
        GenderType = other.GenderType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (person_ == null) {
              person_ = new global::VirtualWallet.Proto.Messages.Person();
            }
            input.ReadMessage(person_);
            break;
          }
          case 16: {
            genderType_ = (global::VirtualWallet.Proto.Messages.NaturalPerson.Types.GenderType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the NaturalPerson message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum GenderType {
        [pbr::OriginalName("MALE")] Male = 0,
        [pbr::OriginalName("FEMALE")] Female = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
