// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/messages/Transaction.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Messages {

  /// <summary>Holder for reflection information generated from proto_defs/messages/Transaction.proto</summary>
  public static partial class TransactionReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/messages/Transaction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransactionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVwcm90b19kZWZzL21lc3NhZ2VzL1RyYW5zYWN0aW9uLnByb3RvEhxWaXJ0",
            "dWFsV2FsbGV0LlByb3RvLk1lc3NhZ2VzGh9nb29nbGUvcHJvdG9idWYvdGlt",
            "ZXN0YW1wLnByb3RvGipwcm90b19kZWZzL21lc3NhZ2VzL1RyYW5zYWN0aW9u",
            "RW50cnkucHJvdG8iuQIKC1RyYW5zYWN0aW9uEigKBHdoZW4YASABKAsyGi5n",
            "b29nbGUucHJvdG9idWYuVGltZXN0YW1wEkcKBHR5cGUYAiABKA4yOS5WaXJ0",
            "dWFsV2FsbGV0LlByb3RvLk1lc3NhZ2VzLlRyYW5zYWN0aW9uLlRyYW5zYWN0",
            "aW9uVHlwZRIOCgZhbW91bnQYAyABKAQSSwoTdHJhbnNhY3Rpb25fZW50cmll",
            "cxgEIAMoCzIuLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuVHJhbnNh",
            "Y3Rpb25FbnRyeSJaCg9UcmFuc2FjdGlvblR5cGUSCgoGVE9QX1VQEAASDAoI",
            "VFJBTlNGRVIQARIMCghQVVJDSEFTRRACEgsKB1BBWU1FTlQQAxISCg5SRUNP",
            "TkNJTElBVElPThAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::VirtualWallet.Proto.Messages.TransactionEntryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualWallet.Proto.Messages.Transaction), global::VirtualWallet.Proto.Messages.Transaction.Parser, new[]{ "When", "Type", "Amount", "TransactionEntries" }, null, new[]{ typeof(global::VirtualWallet.Proto.Messages.Transaction.Types.TransactionType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Transaction : pb::IMessage<Transaction> {
    private static readonly pb::MessageParser<Transaction> _parser = new pb::MessageParser<Transaction>(() => new Transaction());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Transaction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualWallet.Proto.Messages.TransactionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction(Transaction other) : this() {
      When = other.when_ != null ? other.When.Clone() : null;
      type_ = other.type_;
      amount_ = other.amount_;
      transactionEntries_ = other.transactionEntries_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transaction Clone() {
      return new Transaction(this);
    }

    /// <summary>Field number for the "when" field.</summary>
    public const int WhenFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp when_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp When {
      get { return when_; }
      set {
        when_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::VirtualWallet.Proto.Messages.Transaction.Types.TransactionType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VirtualWallet.Proto.Messages.Transaction.Types.TransactionType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 3;
    private ulong amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    /// <summary>Field number for the "transaction_entries" field.</summary>
    public const int TransactionEntriesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::VirtualWallet.Proto.Messages.TransactionEntry> _repeated_transactionEntries_codec
        = pb::FieldCodec.ForMessage(34, global::VirtualWallet.Proto.Messages.TransactionEntry.Parser);
    private readonly pbc::RepeatedField<global::VirtualWallet.Proto.Messages.TransactionEntry> transactionEntries_ = new pbc::RepeatedField<global::VirtualWallet.Proto.Messages.TransactionEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VirtualWallet.Proto.Messages.TransactionEntry> TransactionEntries {
      get { return transactionEntries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Transaction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Transaction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(When, other.When)) return false;
      if (Type != other.Type) return false;
      if (Amount != other.Amount) return false;
      if(!transactionEntries_.Equals(other.transactionEntries_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (when_ != null) hash ^= When.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Amount != 0UL) hash ^= Amount.GetHashCode();
      hash ^= transactionEntries_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (when_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(When);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Amount != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Amount);
      }
      transactionEntries_.WriteTo(output, _repeated_transactionEntries_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (when_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(When);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Amount != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Amount);
      }
      size += transactionEntries_.CalculateSize(_repeated_transactionEntries_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Transaction other) {
      if (other == null) {
        return;
      }
      if (other.when_ != null) {
        if (when_ == null) {
          when_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        When.MergeFrom(other.When);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Amount != 0UL) {
        Amount = other.Amount;
      }
      transactionEntries_.Add(other.transactionEntries_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (when_ == null) {
              when_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(when_);
            break;
          }
          case 16: {
            type_ = (global::VirtualWallet.Proto.Messages.Transaction.Types.TransactionType) input.ReadEnum();
            break;
          }
          case 24: {
            Amount = input.ReadUInt64();
            break;
          }
          case 34: {
            transactionEntries_.AddEntriesFrom(input, _repeated_transactionEntries_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Transaction message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum TransactionType {
        [pbr::OriginalName("TOP_UP")] TopUp = 0,
        [pbr::OriginalName("TRANSFER")] Transfer = 1,
        [pbr::OriginalName("PURCHASE")] Purchase = 2,
        [pbr::OriginalName("PAYMENT")] Payment = 3,
        [pbr::OriginalName("RECONCILIATION")] Reconciliation = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
