// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/messages/TransactionEntry.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Messages {

  /// <summary>Holder for reflection information generated from proto_defs/messages/TransactionEntry.proto</summary>
  public static partial class TransactionEntryReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/messages/TransactionEntry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransactionEntryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipwcm90b19kZWZzL21lc3NhZ2VzL1RyYW5zYWN0aW9uRW50cnkucHJvdG8S",
            "HFZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMaIHByb3RvX2RlZnMvbWVz",
            "c2FnZXMvV2FsbGV0LnByb3RvIsQBChBUcmFuc2FjdGlvbkVudHJ5EjQKBndh",
            "bGxldBgBIAEoCzIkLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuV2Fs",
            "bGV0Eg4KBmFtb3VudBgCIAEoBBJGCgR0eXBlGAMgASgOMjguVmlydHVhbFdh",
            "bGxldC5Qcm90by5NZXNzYWdlcy5UcmFuc2FjdGlvbkVudHJ5LkVudHJ5VHlw",
            "ZSIiCglFbnRyeVR5cGUSCQoFREVCSVQQABIKCgZDUkVESVQQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VirtualWallet.Proto.Messages.WalletReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualWallet.Proto.Messages.TransactionEntry), global::VirtualWallet.Proto.Messages.TransactionEntry.Parser, new[]{ "Wallet", "Amount", "Type" }, null, new[]{ typeof(global::VirtualWallet.Proto.Messages.TransactionEntry.Types.EntryType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TransactionEntry : pb::IMessage<TransactionEntry> {
    private static readonly pb::MessageParser<TransactionEntry> _parser = new pb::MessageParser<TransactionEntry>(() => new TransactionEntry());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransactionEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualWallet.Proto.Messages.TransactionEntryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEntry(TransactionEntry other) : this() {
      Wallet = other.wallet_ != null ? other.Wallet.Clone() : null;
      amount_ = other.amount_;
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEntry Clone() {
      return new TransactionEntry(this);
    }

    /// <summary>Field number for the "wallet" field.</summary>
    public const int WalletFieldNumber = 1;
    private global::VirtualWallet.Proto.Messages.Wallet wallet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VirtualWallet.Proto.Messages.Wallet Wallet {
      get { return wallet_; }
      set {
        wallet_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 2;
    private ulong amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::VirtualWallet.Proto.Messages.TransactionEntry.Types.EntryType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VirtualWallet.Proto.Messages.TransactionEntry.Types.EntryType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransactionEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransactionEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Wallet, other.Wallet)) return false;
      if (Amount != other.Amount) return false;
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (wallet_ != null) hash ^= Wallet.GetHashCode();
      if (Amount != 0UL) hash ^= Amount.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (wallet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Wallet);
      }
      if (Amount != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Amount);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (wallet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Wallet);
      }
      if (Amount != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Amount);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransactionEntry other) {
      if (other == null) {
        return;
      }
      if (other.wallet_ != null) {
        if (wallet_ == null) {
          wallet_ = new global::VirtualWallet.Proto.Messages.Wallet();
        }
        Wallet.MergeFrom(other.Wallet);
      }
      if (other.Amount != 0UL) {
        Amount = other.Amount;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (wallet_ == null) {
              wallet_ = new global::VirtualWallet.Proto.Messages.Wallet();
            }
            input.ReadMessage(wallet_);
            break;
          }
          case 16: {
            Amount = input.ReadUInt64();
            break;
          }
          case 24: {
            type_ = (global::VirtualWallet.Proto.Messages.TransactionEntry.Types.EntryType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TransactionEntry message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum EntryType {
        [pbr::OriginalName("DEBIT")] Debit = 0,
        [pbr::OriginalName("CREDIT")] Credit = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
