// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/grpc/PersonService.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace VirtualWallet.Proto.Grpc {
  public static partial class PersonService
  {
    static readonly string __ServiceName = "VirtualWallet.Proto.Grpc.PersonService";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::VirtualWallet.Proto.Messages.Wallet> __Marshaller_Wallet = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VirtualWallet.Proto.Messages.Wallet.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::VirtualWallet.Proto.Messages.Wallet> __Method_GetWallets = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::VirtualWallet.Proto.Messages.Wallet>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetWallets",
        __Marshaller_Empty,
        __Marshaller_Wallet);

    static readonly grpc::Method<global::VirtualWallet.Proto.Messages.Wallet, global::VirtualWallet.Proto.Messages.Wallet> __Method_AddWallet = new grpc::Method<global::VirtualWallet.Proto.Messages.Wallet, global::VirtualWallet.Proto.Messages.Wallet>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddWallet",
        __Marshaller_Wallet,
        __Marshaller_Wallet);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::VirtualWallet.Proto.Grpc.PersonServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PersonService</summary>
    public abstract partial class PersonServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetWallets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::VirtualWallet.Proto.Messages.Wallet> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::VirtualWallet.Proto.Messages.Wallet> AddWallet(global::VirtualWallet.Proto.Messages.Wallet request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PersonService</summary>
    public partial class PersonServiceClient : grpc::ClientBase<PersonServiceClient>
    {
      /// <summary>Creates a new client for PersonService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PersonServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PersonService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PersonServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PersonServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PersonServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::VirtualWallet.Proto.Messages.Wallet> GetWallets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetWallets(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::VirtualWallet.Proto.Messages.Wallet> GetWallets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetWallets, null, options, request);
      }
      public virtual global::VirtualWallet.Proto.Messages.Wallet AddWallet(global::VirtualWallet.Proto.Messages.Wallet request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddWallet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VirtualWallet.Proto.Messages.Wallet AddWallet(global::VirtualWallet.Proto.Messages.Wallet request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddWallet, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.Wallet> AddWalletAsync(global::VirtualWallet.Proto.Messages.Wallet request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddWalletAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.Wallet> AddWalletAsync(global::VirtualWallet.Proto.Messages.Wallet request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddWallet, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PersonServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PersonServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PersonServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetWallets, serviceImpl.GetWallets)
          .AddMethod(__Method_AddWallet, serviceImpl.AddWallet).Build();
    }

  }
}
#endregion
