// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/grpc/LegalPersonService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Grpc {

  /// <summary>Holder for reflection information generated from proto_defs/grpc/LegalPersonService.proto</summary>
  public static partial class LegalPersonServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/grpc/LegalPersonService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LegalPersonServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cihwcm90b19kZWZzL2dycGMvTGVnYWxQZXJzb25TZXJ2aWNlLnByb3RvEhhW",
            "aXJ0dWFsV2FsbGV0LlByb3RvLkdycGMaG2dvb2dsZS9wcm90b2J1Zi9lbXB0",
            "eS5wcm90bxogcHJvdG9fZGVmcy9tZXNzYWdlcy9QZXJzb24ucHJvdG8y+QIK",
            "EkxlZ2FsUGVyc29uU2VydmljZRJUChJHZXRBbGxMZWdhbFBlcnNvbnMSFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkaJC5WaXJ0dWFsV2FsbGV0LlByb3RvLk1l",
            "c3NhZ2VzLlBlcnNvbjABElcKCUFkZFBlcnNvbhIkLlZpcnR1YWxXYWxsZXQu",
            "UHJvdG8uTWVzc2FnZXMuUGVyc29uGiQuVmlydHVhbFdhbGxldC5Qcm90by5N",
            "ZXNzYWdlcy5QZXJzb24SWAoKVmlld1BlcnNvbhIkLlZpcnR1YWxXYWxsZXQu",
            "UHJvdG8uTWVzc2FnZXMuUGVyc29uGiQuVmlydHVhbFdhbGxldC5Qcm90by5N",
            "ZXNzYWdlcy5QZXJzb24SWgoMVXBkYXRlUGVyc29uEiQuVmlydHVhbFdhbGxl",
            "dC5Qcm90by5NZXNzYWdlcy5QZXJzb24aJC5WaXJ0dWFsV2FsbGV0LlByb3Rv",
            "Lk1lc3NhZ2VzLlBlcnNvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::VirtualWallet.Proto.Messages.PersonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
