// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/grpc/NaturalPersonService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Grpc {

  /// <summary>Holder for reflection information generated from proto_defs/grpc/NaturalPersonService.proto</summary>
  public static partial class NaturalPersonServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/grpc/NaturalPersonService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NaturalPersonServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipwcm90b19kZWZzL2dycGMvTmF0dXJhbFBlcnNvblNlcnZpY2UucHJvdG8S",
            "GFZpcnR1YWxXYWxsZXQuUHJvdG8uR3JwYxobZ29vZ2xlL3Byb3RvYnVmL2Vt",
            "cHR5LnByb3RvGidwcm90b19kZWZzL21lc3NhZ2VzL05hdHVyYWxQZXJzb24u",
            "cHJvdG8ywwMKFE5hdHVyYWxQZXJzb25TZXJ2aWNlEl0KFEdldEFsbE5hdHVy",
            "YWxQZXJzb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GisuVmlydHVhbFdh",
            "bGxldC5Qcm90by5NZXNzYWdlcy5OYXR1cmFsUGVyc29uMAESbAoQQWRkTmF0",
            "dXJhbFBlcnNvbhIrLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuTmF0",
            "dXJhbFBlcnNvbhorLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuTmF0",
            "dXJhbFBlcnNvbhJtChFWaWV3TmF0dXJhbFBlcnNvbhIrLlZpcnR1YWxXYWxs",
            "ZXQuUHJvdG8uTWVzc2FnZXMuTmF0dXJhbFBlcnNvbhorLlZpcnR1YWxXYWxs",
            "ZXQuUHJvdG8uTWVzc2FnZXMuTmF0dXJhbFBlcnNvbhJvChNVcGRhdGVOYXR1",
            "cmFsUGVyc29uEisuVmlydHVhbFdhbGxldC5Qcm90by5NZXNzYWdlcy5OYXR1",
            "cmFsUGVyc29uGisuVmlydHVhbFdhbGxldC5Qcm90by5NZXNzYWdlcy5OYXR1",
            "cmFsUGVyc29uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::VirtualWallet.Proto.Messages.NaturalPersonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
