// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/grpc/NaturalPersonService.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace VirtualWallet.Proto.Grpc {
  public static partial class NaturalPersonService
  {
    static readonly string __ServiceName = "VirtualWallet.Proto.Grpc.NaturalPersonService";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::VirtualWallet.Proto.Messages.NaturalPerson> __Marshaller_NaturalPerson = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VirtualWallet.Proto.Messages.NaturalPerson.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::VirtualWallet.Proto.Messages.NaturalPerson> __Method_GetAllNaturalPersons = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::VirtualWallet.Proto.Messages.NaturalPerson>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllNaturalPersons",
        __Marshaller_Empty,
        __Marshaller_NaturalPerson);

    static readonly grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson> __Method_AddNaturalPerson = new grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddNaturalPerson",
        __Marshaller_NaturalPerson,
        __Marshaller_NaturalPerson);

    static readonly grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson> __Method_ViewNaturalPerson = new grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ViewNaturalPerson",
        __Marshaller_NaturalPerson,
        __Marshaller_NaturalPerson);

    static readonly grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson> __Method_UpdateNaturalPerson = new grpc::Method<global::VirtualWallet.Proto.Messages.NaturalPerson, global::VirtualWallet.Proto.Messages.NaturalPerson>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateNaturalPerson",
        __Marshaller_NaturalPerson,
        __Marshaller_NaturalPerson);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::VirtualWallet.Proto.Grpc.NaturalPersonServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NaturalPersonService</summary>
    public abstract partial class NaturalPersonServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetAllNaturalPersons(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::VirtualWallet.Proto.Messages.NaturalPerson> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::VirtualWallet.Proto.Messages.NaturalPerson> AddNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::VirtualWallet.Proto.Messages.NaturalPerson> ViewNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::VirtualWallet.Proto.Messages.NaturalPerson> UpdateNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NaturalPersonService</summary>
    public partial class NaturalPersonServiceClient : grpc::ClientBase<NaturalPersonServiceClient>
    {
      /// <summary>Creates a new client for NaturalPersonService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NaturalPersonServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NaturalPersonService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NaturalPersonServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NaturalPersonServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NaturalPersonServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::VirtualWallet.Proto.Messages.NaturalPerson> GetAllNaturalPersons(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllNaturalPersons(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::VirtualWallet.Proto.Messages.NaturalPerson> GetAllNaturalPersons(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllNaturalPersons, null, options, request);
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson AddNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddNaturalPerson(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson AddNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddNaturalPerson, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> AddNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddNaturalPersonAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> AddNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddNaturalPerson, null, options, request);
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson ViewNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ViewNaturalPerson(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson ViewNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ViewNaturalPerson, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> ViewNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ViewNaturalPersonAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> ViewNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ViewNaturalPerson, null, options, request);
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson UpdateNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateNaturalPerson(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VirtualWallet.Proto.Messages.NaturalPerson UpdateNaturalPerson(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateNaturalPerson, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> UpdateNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateNaturalPersonAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VirtualWallet.Proto.Messages.NaturalPerson> UpdateNaturalPersonAsync(global::VirtualWallet.Proto.Messages.NaturalPerson request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateNaturalPerson, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NaturalPersonServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NaturalPersonServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NaturalPersonServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllNaturalPersons, serviceImpl.GetAllNaturalPersons)
          .AddMethod(__Method_AddNaturalPerson, serviceImpl.AddNaturalPerson)
          .AddMethod(__Method_ViewNaturalPerson, serviceImpl.ViewNaturalPerson)
          .AddMethod(__Method_UpdateNaturalPerson, serviceImpl.UpdateNaturalPerson).Build();
    }

  }
}
#endregion
