// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defs/grpc/PersonService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualWallet.Proto.Grpc {

  /// <summary>Holder for reflection information generated from proto_defs/grpc/PersonService.proto</summary>
  public static partial class PersonServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_defs/grpc/PersonService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersonServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNwcm90b19kZWZzL2dycGMvUGVyc29uU2VydmljZS5wcm90bxIYVmlydHVh",
            "bFdhbGxldC5Qcm90by5HcnBjGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJv",
            "dG8aIHByb3RvX2RlZnMvbWVzc2FnZXMvV2FsbGV0LnByb3RvMrYBCg1QZXJz",
            "b25TZXJ2aWNlEkwKCkdldFdhbGxldHMSFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkaJC5WaXJ0dWFsV2FsbGV0LlByb3RvLk1lc3NhZ2VzLldhbGxldDABElcK",
            "CUFkZFdhbGxldBIkLlZpcnR1YWxXYWxsZXQuUHJvdG8uTWVzc2FnZXMuV2Fs",
            "bGV0GiQuVmlydHVhbFdhbGxldC5Qcm90by5NZXNzYWdlcy5XYWxsZXRiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::VirtualWallet.Proto.Messages.WalletReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
